language: ruby
rvm:
  - 1.9.3
install:
  - bundle install
script: bundle exec rake site:deploy
after_script: 
env:
  global:
    - GIT_NAME=lacti
    - GIT_EMAIL=lactrious@gmail.com
    - secure: UeQd//JPgGy3hbilS/+Z+4M7ukptyR69QPJGggPFIeOotmDxCDlB2kiBnD3m/ohvMZ+5MtYYuqe4xBSypiyYVZiLO7HC9u+66L1A/S7RP0ckw4eTH3Oz4B5ZQQHUjizMm4/jx/xkDvnrbwtLKgKXJf0MXszYYi5NBHJ+t/6aZWg=
